# Generated by Django 3.2.5 on 2021-07-03 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='com_Date',
            new_name='com_date',
        ),
    ]
