# Generated by Django 3.2.5 on 2021-07-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdlist', '0002_rename_com_date_todolist_com_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='start_date',
            field=models.DateField(),
        ),
    ]
