# Generated by Django 3.2.5 on 2021-07-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdlist', '0003_auto_20210704_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
