# Generated by Django 3.2.5 on 2021-07-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(default='9854555545', max_length=10),
            preserve_default=False,
        ),
    ]
