# Generated by Django 3.2.5 on 2021-07-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_portal', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('experience', models.IntegerField(max_length=2)),
                ('about', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('profile', models.ImageField(default='user/images/profiles/profile_picture.png', null=True, upload_to='vet_portal/images/others')),
            ],
        ),
    ]
