# Generated by Django 3.2.5 on 2021-07-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_portal', '0006_doctor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('profile', models.ImageField(default='user/images/profiles/profile_picture.png', null=True, upload_to='user/images/profiles')),
            ],
        ),
    ]
