# Generated by Django 3.2.5 on 2021-07-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_portal', '0009_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
