# Generated by Django 3.2.5 on 2021-07-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_portal', '0010_auto_20210706_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(default='Sonbhadra', max_length=30),
            preserve_default=False,
        ),
    ]
