# Generated by Django 3.2.5 on 2021-07-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_portal', '0011_doctor_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='price',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
